<?php
	include_once "db_conn.php";
	
	function runQuery($conn, $sql, $msg) {
		if ($conn->query($sql)) {
			echo "Data " . $msg. " successfully<br>";
		} else {
			echo $conn->error . "<br>";
		}
	}
	
	$sql = "TRUNCATE phonedata";
	
	runQuery($conn, $sql, "truncated");

	$sql = "INSERT INTO phonedata (
				image,
				name,
				tech,
				2g_bands,
				3g_net,
				4g_net,
				speed,
				gprs,
				edge,
				announced,
				status,
				dim,
				weight,
				sim,
				display_type,
				display_size,
				res,
				multitouch,
				protect,
				os,
				chipset,
				cpu,
				gpu,
				card_slot,
				internal,
				cam_primary,
				features,
				video,
				cam_secondary,
				alert_types,
				loudspk,
				3o5mm_jack,
				wlan,
				bluetooth,
				gps,
				nfc,
				infr_port,
				radio,
				usb,
				sensors,
				msging,
				browser,
				java,
				battery_type,
				stand_by,
				talk_time,
				music_play,
				colors,
				sar_us,
				sar_eu,
				network_rating,
				launch_rating,
				body_rating,
				display_rating,
				platform_rating,
				mem_rating,
				cam_rating,
				sound_rating,
				comm_rating,
				feat_rating,
				batt_rating,
				misc_rating,
				outOf10
			) VALUES (
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',    
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',    
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				'',
				''
			)";
			
	runQuery($conn, $sql, "inserted");

	/////////////////////////////////////////////////////////////////////////////////////////

	$sql = "INSERT INTO phonedata (
				image,
				name,
				tech,
				2g_bands,
				3g_net,
				4g_net,
				speed,
				gprs,
				edge,
				announced,
				status,
				dim,
				weight,
				sim,
				display_type,
				display_size,
				res,
				multitouch,
				protect,
				os,
				chipset,
				cpu,
				gpu,
				card_slot,
				internal,
				cam_primary,
				features,
				video,
				cam_secondary,
				alert_types,
				loudspk,
				3o5mm_jack,
				wlan,
				bluetooth,
				gps,
				nfc,
				infr_port,
				radio,
				usb,
				sensors,
				msging,
				browser,
				java,
				battery_type,
				stand_by,
				talk_time,
				music_play,
				colors,
				sar_us,
				sar_eu,
				network_rating,
				launch_rating,
				body_rating,
				display_rating,
				platform_rating,
				mem_rating,
				cam_rating,
				sound_rating,
				comm_rating,
				feat_rating,
				batt_rating,
				misc_rating 
			) VALUES (
				'motorola_moto_g4_play.png',
				'Motorola Moto G4 Play',
				'GSM / CDMA / HSPA / LTE',
				'GSM 850 / 900 / 1800 / 1900<br>CDMA 800 / 1900 - XT1607, XT1609',
				'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 - XT1607',
				'LTE band 1(2100), 2(1900), 3(1800), 4(1700/2100), 5(850), 7(2600), 8(900), 12(700), 13(700), 17(700), 25(1900), 26(850), 41(2500) - XT1607<br>LTE band 2(1900), 4(1700/2100), 5(850), 13(700) - XT1609',
				'HSPA 42.2/5.76 Mbps, LTE Cat4 150/50 Mbps, EV-DO Rev.A 3.1 Mbps',
				'Yes',
				'Yes',
				'2016, May',
				'Coming soon',
				'144.4 x 72 x 9.9 mm (5.69 x 2.83 x 0.39 in)',
				'137 g (4.83 oz)',
				'Micro-SIM',
				'IPS LCD capacitive touchscreen, 16M colors',
				'5.0 inches (~66.3% screen-to-body ratio)',
				'720 x 1280 pixels (~294 ppi pixel density)',
				'Yes',
				'',
				'Android OS, v6.0.1 (Marshmallow)',
				'Qualcomm MSM8916 Snapdragon 410',
				'Quad-core 1.2 GHz Cortex-A53',
				'Adreno 306',    
				'microSD, up to 128 GB (dedicated slot)',
				'8/16 GB, 1/2 GB RAM',
				'8 MP, f/2.2, autofocus, LED flash',
				'Geo-tagging, touch focus, face detection, panorama, HDR',
				'1080p@30fps',
				'5 MP, f/2.2',
				'Vibration, MP3, WAV ringtones',
				'Yes',
				'Yes',
				'Wi-Fi 802.11 b/g/n, Wi-Fi Direct, hotspot',
				'v4.1, A2DP, LE',
				'Yes, with A-GPS, GLONASS, BDS',
				'Yes (optional)',
				'No',
				'FM radio',
				'microUSB v2.0',
				'Accelerometer, proximity',
				'SMS(threaded view), MMS, Email, Push Email, IM',
				'HTML5',
				'No',
				'Non-removable Li-Ion 2800 mAh battery',
				'',    
				'',
				'',
				'Black, White',
				'',
				'',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10',
				'10'
			)";
			
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	 $sql = "INSERT INTO phonedata (
				image,
				name,
				tech,
				2g_bands,
				3g_net,
				4g_net,
				speed,
				gprs,
				edge,
				announced,
				status,
				dim,
				weight,
				sim,
				display_type,
				display_size,
				res,
				multitouch,
				protect,
				os,
				chipset,
				cpu,
				gpu,
				card_slot,
				internal,
				cam_primary,
				features,
				video,
				cam_secondary,
				alert_types,
				loudspk,
				3o5mm_jack,
				wlan,
				bluetooth,
				gps,
				nfc,
				infr_port,
				radio,
				usb,
				sensors,
				msging,
				browser,
				java,
				battery_type,
				stand_by,
				talk_time,
				music_play,
				colors,
				sar_us,
				sar_eu,
				network_rating,
				launch_rating,
				body_rating,
				display_rating,
				platform_rating,
				mem_rating,
				cam_rating,
				sound_rating,
				comm_rating,
				feat_rating,
				batt_rating,
				misc_rating
			) VALUES (
				'blu_pure_xl.png',
				'BLU Pure XL',
				'GSM / HSPA / LTE',
				'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',
				'HSDPA 850 / 1700(AWS) / 1900 / 2100',
				'LTE band 2(1900), 4(1700/2100), 7(2600), 17(700)',
				'HSPA 42.2/5.76 Mbps, LTE Cat4 150/50 Mbps',
				'Yes',
				'Yes',
				'2015, September',
				'Available. Released 2015, September',
				'164 x 82.2 x 9.3 mm (6.46 x 3.24 x 0.37 in)',
				'207 g (7.30 oz)',
				'Dual SIM (Micro-SIM, dual stand-by)',
				'AMOLED capacitive touchscreen, 16M colors',
				'6.0 inches (~73.6% screen-to-body ratio)',
				'1440 x 2560 pixels (~490 ppi pixel density)',
				'Yes',
				'Corning Gorilla Glass 3',
				'Android OS, v5.1 (Lollipop)',
				'Mediatek MT6795 Helio X10',
				'Octa-core 2.0 GHz Cortex-A53',
				'PowerVR G6200',    
				'microSD, up to 64 GB (dedicated slot)',
				'64 GB, 3 GB RAM',
				'24 MP, OIS, phase detection autofocus, dual-LED (dual tone) flash',
				'1/2.3" . '"' . " sensor size, geo-tagging, touch focus, face/smile detection, panorama, HDR',
				'2160p@30fps',
				'8 MP, autofocus',
				'Vibration; MP3, WAV ringtones',
				'Yes',
				'Yes<br>- 24-bit/192kHz audio<br>- DTS Surround Sound',
				'Yes',
				'v4.0, A2DP, EDR',
				'Yes, with A-GPS',
				'Yes',
				'FM radio, recording',
				'microUSB v2.0, USB Host',
				'Fingerprint, accelerometer, gyro, proximity, compass',
				'SMS(threaded view), MMS, Email, Push Email, IM',
				'HTML5',
				'No<br>- Active noise cancellation with dedicated mic<br>- MP4/H.264 player<br>- MP3/WAV/eAAC+ player<br>- Photo/video editor<br>- Document viewer',
				'Non-removable Li-Po 3500 mAh battery',
				'Up to 800 h (2G) / Up to 725 h (3G)',
				'Up to 38 h (2G) / Up to 24 h (3G)',    
				'N/A',
				'Black, Gold',
				'N/A',
				'N/A',
				'N/A',
				'8',
				'10',
				'6',
				'9',
				'7',
				'9',
				'7',
				'8',
				'9',
				'9',
				'9',
				'10'
		    )";
			
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	$sql = "INSERT INTO phonedata (
			image,
			name,
			tech,
			2g_bands,
			3g_net,
			4g_net,
			speed,
			gprs,
			edge,
			announced,
			status,
			dim,
			weight,
			sim,
			display_type,
			display_size,
			res,
			multitouch,
			protect,
			os,
			chipset,
			cpu,
			gpu,
			card_slot,
			internal,
			cam_primary,
			features,
			video,
			cam_secondary,
			alert_types,
			loudspk,
			3o5mm_jack,
			wlan,
			bluetooth,
			gps,
			nfc,
			infr_port,
			radio,
			usb,
			sensors,
			msging,
			browser,
			java,
			battery_type,
			stand_by,
			talk_time,
			music_play,
			colors,
			sar_us,
			sar_eu,
			network_rating,
			launch_rating,
			body_rating,
			display_rating,
			platform_rating,
			mem_rating,
			cam_rating,
			sound_rating,
			comm_rating,
			feat_rating,
			batt_rating,
			misc_rating
		) VALUES (
			'htc_one_m9.png',
			'HTC One M9',
			'GSM / CDMA / HSPA / EVDO / LTE',
			'GSM 850 / 900 / 1800 / 1900 <br>CDMA 800 / 1900 - Verizon  ',
			'HSDPA 850 / 900 / 1900 / 2100 - EMEA, Verizon <br> HSDPA 850 / 1900 / 2100 - AT&T <br>HSDPA 850 / 1700(AWS) / 1900 / 2100 - T-Mobile <br>CDMA2000 1xEV-DO - Verizon ',
			'LTE band 1(2100), 3(1800), 5(850), 7(2600), 8(900), 20(800), 28(700), 38(2600), 40(2300), 41(2500) - EMEA<br>LTE band 2(1900), 3(1800), 4(1700/2100), 5(850), 7(2600), 12(700), 17(700), 29(700) - AT&T <br>LTE band 2(1900), 3(1800), 4(1700/2100), 7(2600), 12(700), 17(700) - T-Mobile <br>LTE band 4(1700/2100), 13(700) - Verizon ',
			'HSPA 42.2/21.1 Mbps, LTE Cat6 300/50 Mbps',
			'Yes',
			'Yes',
			'2015, March',
			'Available. Released 2015, March',
			'144.6 x 69.7 x 9.6 mm (5.69 x 2.74 x 0.38 in)',
			'157 g (5.54 oz)',
			'Nano-SIM',
			'Super LCD3 capacitive touchscreen, 16M colors',
			'5.0 inches (~68.4% screen-to-body ratio)',
			'1080 x 1920 pixels (~441 ppi pixel density)',
			'Yes',
			'Corning Gorilla Glass 3<br>- HTC Sense UI 7.0 ',
			'Android OS, v5.0 (Lollipop), upgradable to v6.0 (Marshmallow)',
			'Qualcomm MSM8994 Snapdragon 810',
			'Quad-core 1.5 GHz Cortex-A53 & Quad-core 2.0 GHz Cortex-A57',
			'Adreno 430',    
			'microSD, up to 200 GB (dedicated slot)',
			'32 GB, 3 GB RAM',
			'20 MP, f/2.2, 28mm, autofocus, dual-LED (dual tone) flash, check quality',
			'1/2.4" . '"' . " sensor size, 1.2 µm pixel size, geo-tagging, touch focus, face/smile detection, HDR, panorama',
			'2160p@30fps, 1080p@60fps, 720p@120fps, HDR, stereo sound rec., check quality',
			'4 MP, f/2.0, 27mm, 1/3" . '"' . " sensor size, 2µm pixel size, 1080p@30fps, HDR',
			'Vibration; MP3, WAV ringtones',
			'Yes, with stereo speakers',
			'Yes<br>- 24-bit/192kHz audio ',
			'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, DLNA, hotspot',
			'v4.1, A2DP, aptX',
			'Yes, with A-GPS, GLONASS',
			'Yes',
			'Yes',
			'Stereo FM radio, RDS',
			'microUSB v2.0 (MHL 3.0 TV-out), USB Host',
			'Accelerometer, gyro, proximity, compass',
			'SMS (threaded view), MMS, Email, Push Email',
			'HTML5',
			'No<br>- Fast battery charging: 60% in 30 min (Quick Charge 2.0)<br>- Google Drive (100 GB cloud storage)<br>- Active noise cancellation with dedicated mic<br>- XviD/MP4/H.264/WMV player<br>- MP3/eAAC+/WMA/WAV/FLAC player<br>- Document editor<br>- Photo/video editor',
			'Non-removable Li-Po 2840 mAh battery',
			'Up to 391 h (2G) / Up to 402 h (3G)',    
			'Up to 25 h 20 min (2G) / Up to 21 h 50 min (3G)',
			'N/A',
			'Gunmetal Gray, Amber Gold, Silver/Rose gold, Gold/Pink, Pink',
			'N/A',
			'N/A',
			'10',
			'5/7 launch',
			'9',
			'9',
			'9',
			'10',
			'7',
			'9',
			'10',
			'9',
			'8',
			'8'
		)";
	
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	$sql = "INSERT INTO phonedata (
			image,
			name,
			tech,
			2g_bands,
			3g_net,
			4g_net,
			speed,
			gprs,
			edge,
			announced,
			status,
			dim,
			weight,
			sim,
			display_type,
			display_size,
			res,
			multitouch,
			protect,
			os,
			chipset,
			cpu,
			gpu,
			card_slot,
			internal,
			cam_primary,
			features,
			video,
			cam_secondary,
			alert_types,
			loudspk,
			3o5mm_jack,
			wlan,
			bluetooth,
			gps,
			nfc,
			infr_port,
			radio,
			usb,
			sensors,
			msging,
			browser,
			java,
			battery_type,
			stand_by,
			talk_time,
			music_play,
			colors,
			sar_us,
			sar_eu,
			network_rating,
			launch_rating,
			body_rating,
			display_rating,
			platform_rating,
			mem_rating,
			cam_rating,
			sound_rating,
			comm_rating,
			feat_rating,
			batt_rating,
			misc_rating
		) VALUES (
			'motorola_moto_g4_plus.png',
			'Motorola Moto G4 Plus',
			'GSM / HSPA / LTE',
			'GSM 850 / 900 / 1800 / 1900<br>GSM 850 / 1900 - XT1644 (USA)',
			'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 - XT1644, XT1644 (USA), XT1644 (India)',
			'LTE band 1(2100), 3(1800), 7(2600), 8(900), 20(800) - XT1644<br>LTE band 1(2100), 2(1900), 3(1800), 4(1700/2100), 5(850), 7(2600), 8(900), 12(700), 13(700), 25(1900), 26(850), 41(2500) - XT1644 (USA)',
			'LTE band 1(2100), 3(1800), 5(850), 8(900), 40(2300) - XT1644 (India)',
			'HSPA 42.2/5.76 Mbps, LTE Cat4 150/50 Mbps',
			'Yes',
			'Yes',
			'2016, May',
			'Available. Released 2016, May',
			'153 x 76.6 x 9.8 mm (6.02 x 3.02 x 0.39 in)',
			'155 g (5.47 oz)',
			'Micro-SIM',
			'IPS LCD capacitive touchscreen, 16M colors',
			'5.5 inches (~71.2% screen-to-body ratio)',
			'1080 x 1920 pixels (~401 ppi pixel density)',
			'Yes',
			'Corning Gorilla Glass 3',
			'Android OS, v6.0.1 (Marshmallow)',
			'Qualcomm MSM8952 Snapdragon 617',
			'Quad-core 1.5 GHz Cortex-A53 & quad-core 1.2 GHz Cortex-A53',    
			'Adreno 405',
			'microSD, up to 256 GB (dedicated slot)',
			'16 GB, 2 GB RAM or 32 GB, 3 GB RAM or 64 GB, 4 GB RAM',
			'16 MP, f/2.0, phase detection & laser autofocus, dual-LED (dual tone) flash',
			'Geo-tagging, touch focus, face detection, panorama, auto-HDR',
			'1080p@30fps, HDR',
			'5 MP, f/2.2, auto-HDR',
			'Vibration; MP3, WAV ringtones',
			'Yes',
			'Yes',
			'Wi-Fi 802.11 a/b/g/n, Wi-Fi Direct, hotspot',
			'v4.1, A2DP, LE',
			'Yes, with A-GPS, GLONASS, BDS',
			'No',
			'No',
			'FM radio',
			'microUSB v2.0, USB Host',
			'Fingerprint, accelerometer, gyro, proximity',
			'SMS(threaded view), MMS, Email, Push Email, IM',
			'HTML5',
			'No',
			'Other features with blank field: - Fast battery charging<br>- Active noise cancellation with dedicated mic<br>- MP3/AAC+/WAV/Flac player<br>- MP4/H.264 player<br>- Photo/video editor<br>- Document viewer',    
			'Non-removable Li-Ion 3000 mAh battery',
			'N/A',
			'Black, White',
			'N/A',
			'N/A',
			'8',
			'10',
			'8',
			'9',
			'9',
			'8',
			'7',
			'7',
			'8',
			'9',
			'8',
			'9'
		)";
		
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	 $sql = "INSERT INTO phonedata (
			image,
			name,
			tech,
			2g_bands,
			3g_net,
			4g_net,
			speed,
			gprs,
			edge,
			announced,
			status,
			dim,
			weight,
			sim,
			display_type,
			display_size,
			res,
			multitouch,
			protect,
			os,
			chipset,
			cpu,
			gpu,
			card_slot,
			internal,
			cam_primary,
			features,
			video,
			cam_secondary,
			alert_types,
			loudspk,
			3o5mm_jack,
			wlan,
			bluetooth,
			gps,
			nfc,
			infr_port,
			radio,
			usb,
			sensors,
			msging,
			browser,
			java,
			battery_type,
			stand_by,
			talk_time,
			music_play,
			colors,
			sar_us,
			sar_eu,
			network_rating,
			launch_rating,
			body_rating,
			display_rating,
			platform_rating,
			mem_rating,
			cam_rating,
			sound_rating,
			comm_rating,
			feat_rating,
			batt_rating,
			misc_rating
		) VALUES (
			'motorola_nexus_6.png',
			'Motorola Nexus 6',
			'GSM / CDMA / HSPA / LTE',
			'GSM 850 / 900 / 1800 / 1900 - all models<br>CDMA 800 / 1900 - XT1103',
			'HSDPA 800 / 850 / 900 / 1700 / 1800 / 1900 / 2100 - XT1100<br>HSDPA 850 / 900 / 1700 / 1900 / 2100 - XT1103<br>HSDPA 850 / 900 / 1900 / 2100 - Verizon',
			'LTE band 1(2100), 3(1800), 5(850), 7(2600), 8(900), 9(1800), 19(800), 20(800), 28(700), 41(2500) - XT1100<br>LTE band 2(1900), 3(1800), 4(1700/2100), 5(850), 7(2600), 12(700), 13(700), 17(700), 25(1900), 26(850), 29(700), 41(2500) - XT1103<br>LTE band 4(1700/2100), 13(700) - Verizon',
			'HSPA 42.2/5.76 Mbps, LTE Cat4 150/50 Mbps or LTE Cat6 300/50 Mbps',
			'Yes',
			'Yes',
			'2014, October',
			'Available. Released 2014, November',
			'159.3 x 83 x 10.1 mm (6.27 x 3.27 x 0.40 in)',
			'184 g (6.49 oz)',
			'Nano-SIM',
			'AMOLED capacitive touchscreen, 16M colors',
			'5.96 inches (~74.1% screen-to-body ratio)',
			'1440 x 2560 pixels (~493 ppi pixel density)',
			'Yes',
			'Corning Gorilla Glass 3',
			'Android OS, v5.0 (Lollipop), upgradable to v6.0 (Marshmallow)',
			'Qualcomm Snapdragon 805',
			'Quad-core 2.7 GHz Krait 450',
			'Adreno 420',    
			'No',
			'32/64 GB, 3 GB RAM',
			'13 MP, f/2.0, autofocus, OIS, dual-LED (ring) flash',
			'1.4 µm pixel size, geo-tagging, touch focus, face detection, panorama, HDR',
			'2160p@30fps',
			'2 MP',
			'Vibration; MP3, WAV ringtones',
			'Yes, with stereo speakers',
			'Yes',
			'Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct, DLNA, hotspot',
			'v4.1, A2DP, LE',
			'Yes, with A-GPS, GLONASS',
			'Yes',
			'No',
			'No',
			'microUSB v2.0 (SlimPort), USB Host',
			'Accelerometer, gyro, proximity, compass, barometer',
			'SMS (threaded view), MMS, Email, Push Mail, IM',
			'HTML5',
			'No',
			'Other features with blank field: - Water resistant<br>- Wireless Charging (Qi-enabled)<br>- Active noise cancellation with dedicated mic<br>- MP4/H.264 player<br>- MP3/WAV/eAAC+ player<br>- Photo/video editor<br>- Document editor',
			'Non-removable Li-Po 3220 mAh battery',    
			'Up to 330 h',
			'Up to 24 h',
			'N/A',
			'Midnight Blue, Cloud White',
			'1.47 W/kg (head) 0.93 W/kg (body) ',
			'N/A',
			'8',
			'10',
			'7',
			'9',
			'7',
			'7',
			'8',
			'8',
			'9',
			'8',
			''
		)";
	
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	 $sql = "INSERT INTO phonedata (
			image,
			name,
			tech,
			2g_bands,
			3g_net,
			4g_net,
			speed,
			gprs,
			edge,
			announced,
			status,
			dim,
			weight,
			sim,
			display_type,
			display_size,
			res,
			multitouch,
			protect,
			os,
			chipset,
			cpu,
			gpu,
			card_slot,
			internal,
			cam_primary,
			features,
			video,
			cam_secondary,
			alert_types,
			loudspk,
			3o5mm_jack,
			wlan,
			bluetooth,
			gps,
			nfc,
			infr_port,
			radio,
			usb,
			sensors,
			msging,
			browser,
			java,
			battery_type,
			stand_by,
			talk_time,
			music_play,
			colors,
			sar_us,
			sar_eu,
			network_rating,
			launch_rating,
			body_rating,
			display_rating,
			platform_rating,
			mem_rating,
			cam_rating,
			sound_rating,
			comm_rating,
			feat_rating,
			batt_rating,
			misc_rating
		) VALUES (
			'xolo_black.png',
			'XOLO Black',
			'GSM / HSPA / LTE',
			'GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2',
			'HSDPA 900 / 2100',
			'LTE 1800 TD-LTE 2300',
			'HSPA 42.2/11.5 Mbps, LTE Cat4 150/50 Mbps',
			'Yes',
			'Yes',
			'2015, July',
			'Available. Released 2015, July',
			'155.5 x 76.6 x 7.3 mm (6.12 x 3.02 x 0.29 in)',
			'N/A',
			'Dual SIM (Micro-SIM/Nano-SIM)',
			'IPS LCD capacitive touchscreen, 16M colors',
			'5.5 inches (~69.3% screen-to-body ratio)',
			'1080 x 1920 pixels (~403 ppi pixel density)',
			'Yes',
			'Corning Gorilla Glass 3',
			'Android OS, v5.0 (Lollipop)',
			'Qualcomm MSM8939 Snapdragon 615',
			'Quad-core 1.5 GHz Cortex-A53 & quad-core 1.0 GHz Cortex-A53',
			'Adreno 405',    
			'microSD, up to 32 GB (uses SIM 2 slot)',
			'16 GB, 2 GB RAM',
			'13 MP + 2MP (Dual camera), autofocus, LED flash',
			'Geo-tagging, touch focus, face/smile detection, panorama, HDR',
			'1080p@30fps',
			'5 MP, LED flash',
			'Vibration; MP3, WAV ringtones',
			'Yes',
			'Yes',
			'Wi-Fi 802.11 b/g/n, hotspot',
			'v4.0',
			'Yes, with A-GPS, GLONASS',
			'No',
			'No',
			'FM radio',
			'microUSB v2.0',
			'Accelerometer, gyro, proximity, compass',
			'SMS(threaded view), MMS, Email, Push Email, IM',
			'HTML5',
			'No',
			'Other features with blank field: - DivX/MP4/H.265 player<br>- MP3/WAV/WMA/AAC player<br>- Photo/video editor<br>- Document viewer',
			'Non-removable Li-Po 3200 mAh battery',    
			'Up to 736 h (2G) / Up to 699 h (3G)',
			'Up to 36 h (2G) / Up to 24 h (3G)',
			'Black',
			'N/A',
			'0.13 W/kg (head) 0.27 W/kg (body)',
			'8',
			'10',
			'8',
			'9',
			'7',
			'8',
			'7',
			'7',
			'7',
			'8',
			'8',
			'8'
		)";
	
	runQuery($conn, $sql, "inserted");
	
	//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	
	$conn->close();
?>